### ISSUE TITLE
ERROR: Try To Authenticate Failed

### ISSUE THREAD

**Issue by whybe7** [whybe7/react-laravel-ecommerce#1]
when trying to authenticate from the client (`login/register`) it blocks the request by CORS, even when there is a `CORS` middleware that prevents these errors,

![image](https://user-images.githubusercontent.com/95445743/236860482-9a0f2801-c672-46c1-a5f2-cc06429ca7cf.png)

**Comment by tchisama** [comment]
you can fix this with with allowing the the server to accept and not blocking the requests 
use this headers in the top

header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Headers: *");

**Comment by tchisama** [comment]
oooh it's closed hhhhh sorry i'm new to this shit

**Comment by vvhybe** [comment]
nice suggestion, but I forgot what this project is about 😄
